# Generated by Django 6.0.1 on 2026-01-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_fare',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='distance_km',
        ),
    ]
