# Generated by Django 6.0.1 on 2026-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_created_at_booking_end_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
