# Generated by Django 6.0.1 on 2026-01-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_end_lat_booking_end_lng_booking_start_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='Unknwon'),
            preserve_default=False,
        ),
    ]
